version: '3.8'

services:    
  desplegar-aplicacion:
    image: alpine:latest
    ports:
      - 3030:3000    
    volumes:
      - ../scripts/clone-and-build.sh:/clone-and-build.sh
    command: sh /clone-and-build.sh
