version: '3.8'

services:    
  deploy-app: 
    container_name: Deploy-app_V1
    build:
      context: ../
      dockerfile: Docker/dockerfiles/setup-frontend.dockerfile
    ports:
      - 3030:3000 

  test-branch: 
    container_name: Branch-Spotter-app_1.0
    build:
      context: ../
      dockerfile: Docker/dockerfiles/setup-testing.dockerfile
    ports:
      - 9323:9323   
    depends_on:
      - deploy-app     

  