version: '3.8'

services:     
  deploy-service:
    image: alpine:latest
    restart: always
    ports:
      - 3030:3000  
    volumes:
      - ../scripts/deploy-app.sh:/deploy-app.sh
    command: sh /deploy-app.sh
  
  testing-app-v1:
    image: mcr.microsoft.com/playwright:v1.44.0-jammy
    restart: always
    volumes:
      - ../scripts/setup.sh:/setup.sh
      - ../scripts/docker.setup.sh:/docker.setup.sh
    command: 
      - sh 
      - -c
      - |
        sh /setup.sh
        sh /docker.setup.sh
    depends_on:
      - deploy-service 

