version: '3.8'

services:
  app: 
    image: maxibarbo/spotter_app:1.0
    ports:
      - "${PORT_LOCALHOST_DOCKER_FRONT}:${PORT_LOCALHOST_FRONT}"  
    volumes:
      - ../../Frontend:/app  
    environment:
      - NODE_ENV=development
    env_file:
      - .env 
    depends_on:
      - api

  api:
    image: maxibarbo/spotter_api:1.0
    ports:
      - "${PORT_LOCALHOST_DOCKER_API}:${PORT_LOCALHOST_API}"  
    volumes:
      - ../../Api:/myDB
    environment:
      - NODE_ENV=development
    env_file:
      - .env 
