name: Front Docker-Push CI/CD

on:
  workflow_dispatch:

jobs:

  Docker-Push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Clone GitHub repository
        run: git clone --single-branch --branch testing https://${{ secrets.DOCKER_TOKEN }}@github.com/SpotterGym/Frontend.git
      
      - name: Build Docker image
        run: docker build -t spotter-app -f Frontend/Dockerfile Frontend

      - name: Tags Docker image
        run: |
          docker tag spotter-app ${{ secrets.DOCKER_USER }}/spotter-app:latest
          docker tag spotter-app ${{ secrets.DOCKER_USER }}/spotter-app:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/spotter-app:latest
          docker push ${{ secrets.DOCKER_USER }}/spotter-app:${{ github.sha }}
